site_name: Torn Assistant
theme:
  name: material

nav:
  - ğŸ  Home: index.md

  - ğŸ§­ Decision Tools:
      - ğŸ¢ Company Recommender: decision_flow\company_recommender_workingstats.md
      - ğŸ“‹ Job Picker Wizard: decision_flow/job_picker.md

  - ğŸ¢ Company Profiles:
      - Cruise Line: company_profiles/cruise_line.md
      - Music Store: company_profiles/music_store.md
      - Restaurant: company_profiles/restaurant.md
      - TV Station: company_profiles/tv_station.md
      - Sports Team: company_profiles/sports_team.md
      - Law Firm: company_profiles/law_firm.md
      - Farm: company_profiles/farm.md
      - Tech Company: company_profiles/tech_company.md
      - Software Corporation: company_profiles/software_corporation.md
      - Mechanic: company_profiles/mechanic.md
      - Sweet Shop: company_profiles/sweet_shop.md
      - Game Development: company_profiles/game_development.md
      - Furniture Store: company_profiles/furniture_store.md

  - ğŸ‘¨â€ğŸ’¼ Job Profiles:
      - Medical: company_profiles/medical.md
      - Army: company_profiles/army.md
      - Fire Department: company_profiles/fire_department.md
      - Casino: company_profiles/casino.md
